artnet:
  host: 0.0.0.0
  port: 6454
  universes:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
canvas_height: 0
canvas_width: 2048
frame_rate: 50
gap_x: 0
gap_y: 0
pixel_size: 4
start_x: 0
start_y: 0
test_source:
  enabled: false
  pattern: MOVING_BAR_H
  speed: 1.0
verbose: false
